import type { Metadata } from "next";
import './global.scss'
export const metadata: Metadata = {
  title: "Онкология",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
        {children}
      </body>
    </html>
  );
}
